// Generated by CoffeeScript 1.12.7
(function() {
  var PI, PushUpstream;

  module.exports = PI = function(repo, options, callback) {
    return repo.git("push --set-upstream", {}, [options.remote, options.branch], function(err, stdout, stderr) {
      var status;
      status = new PushUpstream(repo);
      status.parse(stdout);
      return callback(err, status);
    });
  };

  PI.PushUpstream = PushUpstream = (function() {
    function PushUpstream(repo1) {
      this.repo = repo1;
    }

    PushUpstream.prototype.parse = function(text) {
      return text;
    };

    return PushUpstream;

  })();

}).call(this);
