// Generated by CoffeeScript 1.12.7
(function() {
  var R, Remote;

  module.exports = R = function(repo, options, callback) {
    return repo.git("remote", options, function(err, stdout, stderr) {
      var remote, resp;
      remote = new Remote(repo);
      resp = remote.parse(stdout);
      return callback(err, resp);
    });
  };

  R.Remote = Remote = (function() {
    function Remote(repo1) {
      this.repo = repo1;
    }

    Remote.prototype.parse = function(text) {
      var i, len, line, ref;
      this.names = [];
      ref = text.split("\n");
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        if (line) {
          this.names.push(line);
        }
      }
      return this.names;
    };

    return Remote;

  })();

}).call(this);
